# -*- mode: ruby -*-
#
# Vagrantfile - One development machine to rule them all.
#


require 'json'


# Provisioning might need updating for different Fedora
# releases, see the "provision.sh" script for details...
fedora_release = 29

# This is the minimum customization necessary but, to tailor this configuration
# to a specific project, you should also edit the "vagrant/provision.sh" script...
vm_name = "Generic Fedora #{fedora_release}"
vm_hostname = "vagrant-fedora-#{fedora_release}"
vm_size = {"cpus" => 1, "memory" => 1024}


# The box is assumed to be readily usable by default, but all available
# system updates can be installed during provisioning, if necessary...
install_system_updates = true


# Location of the external files used by this script...
vagrant_assets = File.dirname(__FILE__) + "/vagrant"


# Someone may need to (locally) override the VM size for some specific task...
vm_size_override = File.dirname(__FILE__) + "/.vagrant_size.json"
if File.exists?(vm_size_override)
    vm_size = JSON.parse(File.read(vm_size_override))
end


# There is a very high probability that DNF's choice of mirror turns out to
# be a dud. Ensure "fastestmirror" is enabled as early as possible, otherwise
# installing dependencies for the guest additions may take a *very* long time...
begin
    class TweakGuestAdditions < VagrantVbguest::Installers::Fedora
        def install_dependencies_cmd
            'grep -q fastestmirror=true /etc/dnf/dnf.conf || echo fastestmirror=true >>/etc/dnf/dnf.conf; ' \
            'rm -f /var/cache/dnf/fastestmirror.cache; ' \
            'dnf -q clean expire-cache; ' \
            "echo 'Installing build dependencies...'; " \
            'dnf -q -y install ' + dependencies
        end
    end

    # Anything with priority over 5 overrides the default installer...
    VagrantVbguest::Installer.register(TweakGuestAdditions, 100)
rescue NameError
    # The "VagrantVbguest" class won't be available during the first pass,
    # when vagrant is checking for required plugins and stuff like that...
end


Vagrant.configure(2) do |config|
    config.vagrant.plugins = ["vagrant-vbguest", "vagrant-reload"]

    config.vm.box = "fedora/#{fedora_release}-cloud-base"
    config.vm.hostname = vm_hostname

    # The Fedora box defaults to using rsynced folders...
    config.vm.synced_folder ".", "/vagrant", disabled: true

    if install_system_updates
        config.vm.provision "shell", path: "#{vagrant_assets}/updates.sh",
                                     privileged: false  # ...run as the "vagrant" user.
        config.vm.provision :reload
    end

    # Support git operations inside the VM. The file provisioner requires files to exist,
    # which in this case is a good thing as it prevents commits attributed to wrong users...
    config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"

    # Make the local user's SSH key reachable by the main provisioning script...
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"

    # Perform base-system customizations and install project-specific dependencies...
    config.vm.provision "shell", path: "#{vagrant_assets}/provision.sh",
                                 privileged: false  # ...run as the "vagrant" user.

    config.ssh.forward_agent = true
    config.ssh.keep_alive = true


    config.vm.provider "virtualbox" do |vm, override|
        vm.name = vm_name
        vm.gui = false

        vm.memory = vm_size["memory"]
        vm.cpus = vm_size["cpus"]
        vm.default_nic_type = "virtio"

        # Resolve names using the host's stub resolver (useful for VPNs)...
        vm.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]

        # Install guest additions automatically...
        override.vbguest.auto_update = true

        # Expose the VM to the host instead of forwarding many ports individually
        # for complex projects. The provisioning script will setup Avahi/mDNS to
        # make the guest VM easily accessible through a "*.local" domain...
        override.vm.network "private_network", type: "dhcp"

        # Make the current directory visible (and editable) inside the VM...
        override.vm.synced_folder ".", "/home/vagrant/shared"
    end
end


# vim: set expandtab ts=4 sw=4 ft=ruby:
