# -*- mode: ruby -*-
#
# Vagrantfile - One development machine to rule them all.
#


require 'json'


# Provisioning might need updating for different Fedora releases, see
# the "provision.sh" script for details. Only Fedora 35 was tested...
fedora_release = 40

# This is the minimum customization necessary but, to tailor this configuration
# to a specific project, you should also edit the "vagrant/provision.sh" script...
vm_name = "Generic Fedora #{fedora_release}"
vm_hostname = "vagrant-fedora-#{fedora_release}"
vm_size = {"cpus" => 1, "memory" => 1024}

# Fedora boxes aren't usually updated after initial release...
install_system_updates = false


# Location of the external files used by this script...
vagrant_assets = File.dirname(__FILE__) + "/vagrant"


# Someone may need to (locally) override the VM size for some specific task...
vm_size_override = File.dirname(__FILE__) + "/.vagrant_size.json"
if File.exist?(vm_size_override)
    vm_size = JSON.parse(File.read(vm_size_override))
end


Vagrant.configure(2) do |config|
    config.vm.box = "bento/fedora-#{fedora_release}"
    config.vm.hostname = vm_hostname

    # The Fedora box defaults to using rsynced folders...
    config.vm.synced_folder ".", "/vagrant", disabled: true

    if install_system_updates
        config.vm.provision "shell", path: "#{vagrant_assets}/updates.sh", reboot: true,
                                     privileged: false  # ...run as the "vagrant" user.
    end

    # Support git operations inside the VM...
    if File::exist?(File::expand_path("~/.gitconfig"))
        config.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"
    end

    # Make the local user's SSH public keys reachable by the main provisioning script...
    Dir::chdir(File::expand_path("~/.ssh")) do
        Dir::glob("*.pub").each do |pubkey|
            config.vm.provision "file", source: File::join("~/.ssh", pubkey), destination: "/tmp/"
        end
    end

    # Perform base-system customizations and install project-specific dependencies...
    config.vm.provision "shell", path: "#{vagrant_assets}/provision.sh",
                                 env: {"HOST_TIMEZONE" => Time.now.zone},
                                 privileged: false,  # ...run as the "vagrant" user.
                                 binary: true  # ...don't convert to CRLF on Windows.

    config.vm.post_up_message = "VM available from the host at: #{vm_hostname}.local"

    config.ssh.forward_agent = true
    config.ssh.keep_alive = true

    config.vm.provider "virtualbox" do |vm, override|
        vm.name = vm_name
        vm.gui = false

        vm.memory = vm_size["memory"]
        vm.cpus = vm_size["cpus"]
        vm.default_nic_type = "virtio"

        #
        # Resolve names using the host's configured DNS resolvers, but hide their actual IP
        # addresses from the guest (useful if they come from DHCP and are subject to change).
        #
        # It is sometimes useful to use "--natdnshostresolver1" instead, to use the host's
        # stub resolver APIs (i.e. when using VPN software that hijacks DNS resolution), but
        # beware that this comes with some caveats (e.g. musl doesn't deal with it very well).
        #
        vm.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

        # No need for audio in a server-type VM...
        vm.customize ["modifyvm", :id, "--audio", "none"]

        # The guest additions are already built-in...
        if Vagrant.has_plugin?("vagrant-vbguest")
            override.vbguest.auto_update = false
            override.vbguest.allow_downgrade = false
        end

        # Expose the VM to the host instead of forwarding many ports individually
        # for complex projects. The provisioning script will setup Avahi/mDNS to
        # make the guest VM easily accessible through a "*.local" domain...
        override.vm.network "private_network", type: "dhcp", name: Vagrant::Util::Platform.windows? ? nil : "vboxnet0"

        # Even though we set the default NIC type above, it doesn't seem to always apply...
        vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vm.customize ["modifyvm", :id, "--nictype2", "virtio"]

        # Make the current directory visible (and editable) inside the VM...
        override.vm.synced_folder ".", "/home/vagrant/shared", SharedFoldersEnableSymlinksCreate: false
    end
end


# vim: set expandtab ts=4 sw=4 ft=ruby:
